insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');


insert into author (bookId, authorName) values ('1', 'Drucie Goodbourn');
insert into author (bookId, authorName) values ('2', 'Marcia Aggiss');
insert into author (bookId, authorName) values ('3', 'Giovanni Bigg');
insert into author (bookId, authorName) values ('4', 'Duffie Eynon');
insert into author (bookId, authorName) values ('5', 'Anselma McKennan');
insert into author (bookId, authorName) values ('6', 'Gert Kira');
insert into author (bookId, authorName) values ('7', 'Clerc Djakovic');
insert into author (bookId, authorName) values ('8', 'Stacee Elsy');
insert into author (bookId, authorName) values ('9', 'Dorotea Bonhill');
insert into author (bookId, authorName) values ('10', 'Minni Bunney');
insert into author (bookId, authorName) values ('11', 'Berty Gandley');
insert into author (bookId, authorName) values ('12', 'Raynard Tesdale');
insert into author (bookId, authorName) values ('13', 'Joanna Hutfield');
insert into author (bookId, authorName) values ('14', 'Dannie Glidder');
insert into author (bookId, authorName) values ('15', 'Timmie Adshede');
insert into author (bookId, authorName) values ('16', 'Fernando Neads');
insert into author (bookId, authorName) values ('17', 'Teddy Guilliland');
insert into author (bookId, authorName) values ('18', 'Paloma Grebert');
insert into author (bookId, authorName) values ('19', 'Kristos Usher');
insert into author (bookId, authorName) values ('20', 'Darcey Rohmer');
insert into author (bookId, authorName) values ('21', 'Cristie Isacsson');
insert into author (bookId, authorName) values ('22', 'Lindsay Coutthart');
insert into author (bookId, authorName) values ('23', 'Helyn Schneidar');
insert into author (bookId, authorName) values ('24', 'Bette-ann Askem');
insert into author (bookId, authorName) values ('25', 'Dom Robuchon');

SELECT * FROM books INNER JOIN author ON books.id=author.bookId
